require 'ig-crypto-utils'

require_relative '../../../api/utils/hash_generator'

require_relative '../../../tests/builders/participant_builder'
require_relative '../../../tests/builders/signature_builder'
require_relative '../../../tests/builders/trigger_builder'
require_relative '../../../tests/builders/contract_builder'
require_relative '../../../tests/builders/key_builder'
require_relative '../../../tests/builders/wallet_builder'
require_relative '../../../tests/builders/transaction_builder'
require_relative '../../../tests/builders/webhook_builder'
require_relative '../../../tests/builders/condition_builder'
require_relative '../../../tests/builders/contract_builder'
require_relative '../../../tests/builders/secret_builder'

class StepHelper

  # deprecated - use real tokens generated by local ID-IO!
  def create_canned_auth_payload
    '{"token":"8f89d90f-8fa2-4df4-a67e-3d17842b51ea","auth":"QoBmzwvIIg3g2vhEWhAfgDlHQysKczA3YADZNC/P1YuOqiKQafT1MOpsdA6L\nIKlLVShoRJn8Z2fDSHvruq+JbSxfmfgbwvq5sEVj2GqUVREGooHAt1knQg7F\nUsUkHGPc8/qlRVrWmoNMxNeimzFm6w0PMvCgcChJ1lYcqVFnpgZ5MBPdWPeX\nPMk4lg+GX0Bn6/NLcdBnUjYKfCK9XX+NMTj4PvL2X+ukQ7GZ8L1nW2iGQSQE\ncZxTg5+fr+UV/fnap0GR270WbSHhXibwsZ/WFcRc+yN6toyJrIY8Ng3JYenM\nN0TltZuM8DLkytJojkXlHh40om9wxpzhkX4MxpIqK63ynkgwKp2Y3sxRpLmV\nGBDeF35e6EGypEIevNZTGmBOxIBNw+JggmpBZvIn1LO+ZsRLTI0BuN1iYa0u\nXdULDXBge5Ua1Y3oobqh1JX470ulu+foOSApJMD0Tm4VV17l34GoLjPmKtlu\n2vBGPZorFIRfvt2fTi7dkLqK8JIW1E/YXbG9b1kWsIlE7y75MAngKw0PWEMW\n+plplYVXbJLQTJYNKzAc/FFowkZPe6mdQ1G+MAr+5rpeWBXfoTa9Qp5xAVcn\nSKFGVj44i81DZ5H8vs1matNJbPFA1jAI7e9WaT8E6zbhlIBot1b1yfiFDcpW\ntR+STxuoT6IeqhB2JenDfup5LDjBv5/yL5o4pI6eLh8Y0bAxP0LOD4KyOo7v\nKXK67t4ZFOVVDYd681X6Drn50umhFSnvp7uJal0faWiqgfyB4pGUgRrryk3J\nHjceT64w5g==\n","iv":"nSzqJwutSSBsKwcl15q3IQ==\n"}'
  end

  def create_key_pair
    KeyBuilder.new.build_pair
  end

  def create_secret(fragments, threshold)
    SecretBuilder.new.with_fragments(fragments).with_threshold(threshold).build
  end

  def create_wallet(secret)
    WalletBuilder.new.with_address(HashGenerator.new.generate_uuid)
        .with_secret(secret).build
  end

  def create_participant(roles, external_id, key, wallet)
    ParticipantBuilder.new.with_roles(roles)
        .with_external_id(external_id)
        .with_public_key(key)
        .with_wallet(wallet)
        .build
  end

  def create_contract_signature(participant_external_id)
    SignatureBuilder.new.with_participant_external_id(participant_external_id).build
  end

  def create_updated_contract_signature(data, private_key)
    ecdsa_util = CryptoUtils::EcdsaUtil.new

    encoded_digest = HashGenerator.new.generate_hash data
    signature = ecdsa_util.sign encoded_digest, private_key

    SignatureBuilder.new.with_value(signature).with_digest(encoded_digest).build
  end

  def create_condition_signature(participant_external_id, type, delegated_by_id)
    SignatureBuilder.new.with_participant_external_id(participant_external_id)
        .with_type(type)
        .with_delegated_by_external_id(delegated_by_id)
        .build
  end

  def create_updated_condition_signature(data, private_key)
    ecdsa_util = CryptoUtils::EcdsaUtil.new

    encoded_digest = HashGenerator.new.generate_hash data
    signature = ecdsa_util.sign encoded_digest, private_key

    SignatureBuilder.new.with_value(signature).with_digest(encoded_digest).build
  end

  def create_webhook(uri)
    WebhookBuilder.new.with_uri(uri).build
  end

  def create_transaction(from_participant, to_participant, currency, amount)
    TransactionBuilder.new
        .with_from_participant_external_id(from_participant)
        .with_to_participant_external_id(to_participant)
        .with_currency(currency)
        .with_amount(amount)
        .build
  end

  def create_trigger(webhooks, transactions)
    TriggerBuilder.new
        .with_webhooks(webhooks)
        .with_transactions(transactions)
        .build
  end

  def create_condition(trigger, name, description, sequence_number, signatures, expires)
    ConditionBuilder.new
        .with_trigger(trigger)
        .with_name(name)
        .with_description(description)
        .with_sequence_number(sequence_number)
        .with_signatures(signatures)
        .with_expires(expires).build
  end

  def create_contract(name, description, expires, participants, conditions, signatures)
    ContractBuilder.new.with_name(name)
        .with_description(description)
        .with_expires(expires)
        .with_participants(participants)
        .with_conditions(conditions)
        .with_signatures(signatures)
        .build
  end
end