require 'sinatra/base'
require './api/services/config_service'
require './api/services/token_service'

module Sinatra
  module AuthRoutes
    def self.registered(app)

      #this filter applies to everything except options, registration of new users and documentation
      app.before do

        method = request.request_method
        path = request.path_info

        if (method == 'OPTIONS') ||
            (method == 'POST' && path == '/users') ||
            (method == 'POST' && path == '/tokens') ||
            (method == 'GET' && (path.include? '/tokens/'))
          return
        else
          auth_header = env['HTTP_AUTHORIZATION']

          is_static = lambda { |path_info|
            return true if (path_info == '/' && method == 'GET')
            return true if (path_info == '/favicon.ico' && method == 'GET')
            return true if path_info.include? '/docs'
            return true if path_info.include? '/fonts/'
            return true if path_info.include? '/css/'
            return true if path_info.include? '/js/'
            return true if path_info.include? '/images/'
            false
          }

          unless is_static.call(path)

            # all other routes are the API - these require an Authorization token

            if auth_header == nil
              halt 401, 'Unauthorized!'
            end

            # the auth token to be used here is generated by the following process:
            #   1. a user logs in to ID-IO with username/password OR username/signed challenge
            #   2. the resulting auth payload received from ID-IO
            #       is then POSTed to the /tokens route of the contract API
            #   3. the contract API then decrypts and generates an access token
            #   4. this access token is placed in the Authorization header of subsequent requests
            #       and used here:

            token = TokenService.new.get_token(auth_header)

            if token == nil
              (halt 401, 'Unauthorized!')
            else
              # the current user context is set using the user id of the token
              user = UserService.new.get_by_id token[:user_id]

              @current_user_id = token[:user_id]
              @current_user_role = user[:role]
            end
          end
        end
      end

    end
  end

  register AuthRoutes
end